### ISSUE TITLE
Implement authorization via fastify-casbin

### ISSUE THREAD

**Issue by simoneb** [nearform/titus#657]
Please refer  to #594 as a starting point and implement something similar for auth0 and azure as well.

### Expectations

- [ ] the UI should show a button which performs a dummy action in the backend
- [ ] remove the unnecessary logic around listing and deleting users that's in #594, we don't want to overlap the authorization functionality and the interaction with the auth providers
- [ ] the dummy action in the backend should check if the authenticated user belongs to the "admin" group in the authentication provider (note that groups are called roles in auth0)
- [ ] if the authenticated user belongs to the admin group the action is allowed, otherwise an error 403 is returned and displayed in the UI
- [ ] the authorization check is done with fastify-casbin and corresponding casbin models and policies. different providers may need different models and policies
- [ ] in #594 you can see that with Cognito checking the association between a user and a group is easy because it's embedded in the JWT token generated by Cognito. This doesn't happen with auth0 and azure. Consider either using a different approach for auth0 and azure or using a unique approach for all 3, which would consist in loading the information about the association user<->group at runtime using the authentication provider APIs and using that for carrying out the authorization checks
- [ ] consider different approaches at writing the casbin policy/model. the way it's done in #594 consists of a single policy but policies could even be loaded at runtime and added programmatically to casbin
